feat: add readme
probcomp/inferenceql.viz.stream pull request #15
Opened 2022-04-01 04:10 UTC by harishtella

2022-04-01 04:23 UTC, zane requested changes
Looks great! 

Could you make the scope `docs:` instead of `feat:`?

2022-04-01 23:35 UTC, harishtella commented
Sure thing. Knew there had to be a better tag.

2022-04-05 20:07 UTC, harishtella commented
Ok, should be good.

2022-04-06 03:13 UTC, zane approved these changes

2022-04-06 03:13 UTC, merged